### ISSUE TITLE
Unlocking Joystick inputs applies incorrect defaults

### ISSUE THREAD

**Issue by Poofjunior** [AllenNeuralDynamics/exa-spim-control#41]
In our setup, when we restore the joystick settings, the scroll wheel will be tied to two devices, which is not correct.

We should get the current mapping, save it, lock out, and then unlock and restore the prior mapping.

**Comment by adamkglaser** [comment]
@Poofjunior I forgot about this one, but its been a bit of a pain recently if I forgot to manually remap these after each scan. If you have more free time from other projects later in the week, this would be a good one to dig into.

**Comment by Poofjunior** [comment]
All right I'm calling this one done!
