### ISSUE TITLE
[precheck] - check XYZ bounds

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/exa-spim-control#46]
Check requested XYZ bounds against some hard bounds set in the config file or driver to prevent stage collisions

**Comment by adamkglaser** [comment]
Is this done?

**Comment by micahwoodard** [comment]
Yep in the  [exaSPIM-UI](https://github.com/AllenNeuralDynamics/exaSpim-UI/blob/main/widgets/volumeteric_acquisition.py) repo. It should let you know on the limits tab and when starting the scan if the position with the volume will be out of bounds and in what directions. When pressing start scan, it doesn't actually start the scan if it's out of bounds
